python:
  - "2.7"

env:
  - DEPS="numpy scikit-learn  matplotlib bibtexparser feedparser"

#install the required modules
install:
  - python setup.py install --user

#run some test scripts
script: 
  - which nosetests
