python:
  - "2.7"

virtualenv:
  system_site_packages: true

#install the required modules
install:
  - apt-get install python-scipy python-numpy python-nose python-scikits-learn
  - pip install --user bibtexparser feedparser
  - python setup.py install --user

#run some test scripts
script: 
  - which nosetests
  - nosetests test
