python:
  - "2.7"

virtualenv:
  system_site_packages: true

#install the required modules
install:
  - sudo apt-get install python-scipy python-numpy python-nose
  - pip install --user bibtexparser feedparser scikit-learn
  - python setup.py install --user

#run some test scripts
script:
  - nosetests test
