python:
  - "2.7"

virtualenv:
  system_site_packages: true

#install the required modules
install:
  - export SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
  - sudo apt-get install python-scipy python-numpy python-nose
  - pip install --user bibtexparser feedparser nose scikit-learn
  - python setup.py install --user

#run some test scripts
script: 
  - which nosetests
  - python test/incremental_training_test.py
  - nosetests test
