python:
  - "2.7"

env:
  - DEPS="numpy scikit-learn  bibtexparser feedparser"

#install the required modules
install:
  - pip install --user $DEPS
  - python setup.py install --user

#run some test scripts
script: 
  - which nosetests
  - nosetests test
